server:
  port: 8922
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  main:
    allow-circular-references: true
  application:
    name: sys_gateway
  datasource:
    url: jdbc:mysql://localhost:3306/auth_system_v2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #    url: jdbc:mysql://43.138.149.121:3306/auth_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: lwxMysql
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
  cloud:
    nacos:
      discovery:
        #        server-addr: 43.138.149.121:8848
        server-addr: 127.0.0.1:8848
        locator:
          lower-case-service-id: true
        register-enabled: true
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway可以发现nacos中的微服务
      routes:
        - id: shop_route
          uri: lb://shop # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/shop/**
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/order/**
        # 权限系统路由
        - id: sys_manager_route
          uri: lb://manager
          predicates:
            - Path=/manager/**
        - id: sys_external_route
          uri: lb://external
          predicates:
            - Path=/external/**

mybatis-plus:
  mapper-locations:  classpath*:org/example/common/mappers/*.xml
  typeAliasesPackage: org.example.domain
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

